server:
  port: 8769

spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
#心跳  
  server: 
    enable-self-preservation: true
    renewalPercentThreshold: 0.49
    peer-node-read-timeout-ms: 1000