server:
  port: 8763

spring:
  application:
    name: service-lucy

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
# actuator 2.x 以后endpoints 全部在/actuator下，可以通过management.endpoints.web.base-path修改    